_merge: deep

description: A framework-agnostic CSS foundation. Socle is French for foundation.

search:
  enable: true
  layout: offcanvas
  showImages: false
  sort: true

docs:
  sidebarmenu: true
